using AutoMapper;
using BookStoreApp.API.Data;
using BookStoreApp.API.Data.Models.Author;

namespace BookStoreApp.API.Configurations;

public class MapperConfig : Profile //cip...19
{
    public MapperConfig()
    {
        CreateMap<AuthorCreateDto, Author>().ReverseMap(); // Maps AuthorCreateDto to Author and vice versa
            //copilot: .ForMember(dest => dest.Id, opt => opt.Ignore()); // Ignore Id as it will be generated by the database  
        CreateMap<AuthorUpdateDto, Author>().ReverseMap(); // Maps AuthorUpdateDto to Author and vice versa
        CreateMap<AuthorReadOnlyDto, Author>().ReverseMap(); // Maps AuthorReadOnlyDto to Author and vice versa
    }
}
