# .github/workflows/deploy-api.yml
name: Deploy API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore BookStoreApp.API/BookStoreApp.API.csproj

      - name: Build
        run: dotnet build --configuration Release BookStoreApp.API/BookStoreApp.API.csproj

      - name: Publish
        run: dotnet publish BookStoreApp.API/BookStoreApp.API.csproj -c Release -o ./publish

      - name: Deploy to Azure API
        uses: azure/webapps-deploy@v3
        with:
          app-name: BookStoreAppKevApi
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ./publish
