name: Build and deploy ASP.Net Core app to Azure Web App - BookStoreAppKevAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Clean, build, and publish
        run: |
          dotnet clean BookStoreApp.API/BookStoreApp.API.csproj
          dotnet build BookStoreApp.API/BookStoreApp.API.csproj --configuration Release
          dotnet publish BookStoreApp.API/BookStoreApp.API.csproj --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55F5763318CE4085BEA52939EF85CF33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65A5D02869BC4857A1DF14A0860BA0AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B5425D228824B4B81A422DA0746A778 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BookStoreAppKevAPI'
          slot-name: 'Production'
          package: ./.net-app